In [6]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, MaxPool2D, Conv2D, Dense, Reshape, Dropout
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from sklearn import datasets
from sklearn import metrics

# Credit scoring system

In [7]:
import requests
url = 'https://raw.githubusercontent.com/Amitabh23/Machine-Learning-Project/master/Credit.csv'
res = requests.get(url, allow_redirects=True)
with open('Credit.csv','wb') as file:
    file.write(res.content)
df = pd.read_csv('Credit.csv')

In [8]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [9]:
X= df.iloc[:,:-1].values
y= df.iloc[:,24].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
import tensorflow.keras
classifier = Sequential()

classifier.add(Dense(12,activation= 'relu',input_dim=24))
classifier.add(Dense(7,activation= 'relu'))
classifier.add(Dense(1,activation= 'sigmoid'))

classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

classifier.fit(X_train, y_train,batch_size=10,epochs = 20)

Epoch 1/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4835 - accuracy: 0.8015
Epoch 2/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4467 - accuracy: 0.8153
Epoch 3/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4411 - accuracy: 0.8169
Epoch 4/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4375 - accuracy: 0.8184
Epoch 5/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4351 - accuracy: 0.8194
Epoch 6/20
2250/2250 [==============================] - 5s 2ms/step - loss: 0.4334 - accuracy: 0.8191
Epoch 7/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4319 - accuracy: 0.8202
Epoch 8/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4314 - accuracy: 0.8192
Epoch 9/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4301 - accuracy: 0.8194
Epoch 10/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4297 - accuracy: 0.8192
Epoch 11/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4286 - accuracy: 0.8190
Epoch 12/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4284 - accuracy: 0.8196
Epoch 13/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4280 - accuracy: 0.8202
Epoch 14/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4275 - accuracy: 0.8200
Epoch 15/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4270 - accuracy: 0.8201
Epoch 16/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4267 - accuracy: 0.8215
Epoch 17/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4263 - accuracy: 0.8210
Epoch 18/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4255 - accuracy: 0.8215
Epoch 19/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4250 - accuracy: 0.8202
Epoch 20/20
2250/2250 [==============================] - 4s 2ms/step - loss: 0.4251 - accuracy: 0.8197

In [19]:
classifier.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_12 (Dense)             (None, 12)                300
_________________________________________________________________
dense_13 (Dense)             (None, 7)                 91
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 8
=================================================================
Total params: 399
Trainable params: 399
Non-trainable params: 0
_________________________________________________________________

In [20]:
#predicting the test set result

y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

In [21]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(metrics.classification_report(y_test,y_pred))
print(metrics.confusion_matrix(y_test,y_pred ))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      5880
           1       0.66      0.36      0.47      1620

    accuracy                           0.82      7500
   macro avg       0.75      0.65      0.68      7500
weighted avg       0.80      0.82      0.80      7500

[[5585  295]
 [1039  581]]